POST http://localhost:5000/api/v1/auth/signup
Content-Type: application/json

{
  "username": "testmsi",
  "password": "testmsi"
}

###Log out request
GET http://localhost:5000/api/v1/auth/logout

###Refresh token request
POST http://localhost:5000/api/v1/auth/refreshToken
Content-Type: application/json

{
  "username": "testmsi"
}

###Login request
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "username": "testmsi",
  "password": "testmsi"
}